import React, { useState } from 'react';
import { AnalysisResult } from '../types';
import { Copy, Heart, Smile, Sparkles, Briefcase, ExternalLink, Skull, Zap, Share2, Check, Calendar } from 'lucide-react';

interface ResultCardProps {
  result: AnalysisResult;
  theme?: 'light' | 'dark';
}

const ToneIcon = ({ tone }: { tone: string }) => {
  const t = tone.toLowerCase();
  if (t.includes('flirt')) return <Heart className="w-4 h-4 text-pink-500" />;
  if (t.includes('fun') || t.includes('wit')) return <Smile className="w-4 h-4 text-yellow-500" />;
  if (t.includes('pro')) return <Briefcase className="w-4 h-4 text-blue-500" />;
  if (t.includes('unhinged')) return <Skull className="w-4 h-4 text-red-500" />;
  if (t.includes('casual')) return <Zap className="w-4 h-4 text-green-400" />;
  if (t.includes('date') || t.includes('plan')) return <Calendar className="w-4 h-4 text-emerald-400" />;
  return <Sparkles className="w-4 h-4 text-purple-500" />;
};

const ResultCard: React.FC<ResultCardProps> = ({ result, theme = 'dark' }) => {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const copyToClipboard = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const copyAll = () => {
    const allText = result.suggestions.map(s => `${s.tone}: ${s.reply}`).join('\n\n');
    navigator.clipboard.writeText(allText);
    alert("All suggestions copied!");
  };

  const shareResult = async () => {
    const text = `Check out these rizz lines generated by RizzMaster AI:\n\n` +
      result.suggestions.map(s => `"${s.reply}"`).join('\n') +
      `\n\nGenerated by RizzMaster AI`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'RizzMaster AI Results',
          text: text,
          url: window.location.href
        });
      } catch (err) {
        console.log('Error sharing:', err);
      }
    } else {
      copyAll();
    }
  };

  // Helper to render text with simple formatting
  const renderFormattedText = (text: string) => {
    return text.split('\n').map((line, i) => (
      <span key={i} className="block min-h-[1.2em]">
        {line.split(/(\*\*.*?\*\*)/).map((part, j) => {
          if (part.startsWith('**') && part.endsWith('**')) {
            return <strong key={j} className={theme === 'dark' ? 'text-white' : 'text-slate-900'}>{part.slice(2, -2)}</strong>;
          }
          return part;
        })}
      </span>
    ));
  };

  return (
    <div className="flex flex-col gap-6 animate-fade-in-up w-full">
      {/* Summary Section */}
      {result.summary && (
        <div className={`flex items-start gap-3 p-4 rounded-xl border transition-all hover:scale-[1.01] ${theme === 'dark'
            ? 'bg-slate-900/50 border-slate-800/50 backdrop-blur-sm'
            : 'bg-purple-50/50 border-purple-100'
          }`}>
          <div className="mt-1 shrink-0">
            <Sparkles className={theme === 'dark' ? 'w-4 h-4 text-purple-400' : 'w-4 h-4 text-purple-500'} />
          </div>
          <p className={`text-sm italic leading-relaxed ${theme === 'dark' ? 'text-slate-300' : 'text-slate-700'
            }`}>{result.summary}</p>
        </div>
      )}

      {/* Suggestions Grid */}
      <div className="flex flex-col gap-4">
        {result.suggestions.map((s, idx) => {
          const isDatePlan = s.tone.toLowerCase().includes('date') || s.tone.toLowerCase().includes('plan');

          return (
            <div
              key={idx}
              className={`rounded-2xl p-4 md:p-5 border transition-all duration-300 group hover:scale-[1.02] ${isDatePlan
                  ? theme === 'dark'
                    ? 'bg-slate-900/90 border-emerald-500/30 hover:border-emerald-500/50 hover:shadow-[0_0_24px_rgba(16,185,129,0.15)]'
                    : 'bg-emerald-50/50 border-emerald-200 hover:border-emerald-300 hover:shadow-lg hover:shadow-emerald-100'
                  : theme === 'dark'
                    ? 'bg-slate-800/80 backdrop-blur-sm border-slate-700/50 hover:border-pink-500/40 hover:shadow-[0_0_20px_rgba(236,72,153,0.15)]'
                    : 'bg-white/80 backdrop-blur-sm border-gray-200 hover:border-pink-300 hover:shadow-lg hover:shadow-pink-100'
                }`}
            >
              <div className="flex justify-between items-start gap-4">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2.5 mb-3">
                    <ToneIcon tone={s.tone} />
                    <span className={`text-xs font-extrabold uppercase tracking-wider truncate ${isDatePlan
                        ? 'text-emerald-500'
                        : s.tone.toLowerCase().includes('flirty')
                          ? 'text-pink-500'
                          : s.tone.toLowerCase().includes('unhinged')
                            ? 'text-red-500'
                            : theme === 'dark' ? 'text-slate-400' : 'text-slate-600'
                      }`}>
                      {s.tone}
                    </span>
                  </div>

                  <div className={`font-sans leading-relaxed selection:bg-pink-500/30 break-words ${isDatePlan
                      ? theme === 'dark'
                        ? 'text-base md:text-lg text-slate-200'
                        : 'text-base md:text-lg text-slate-800'
                      : theme === 'dark'
                        ? 'text-lg md:text-xl font-semibold text-white'
                        : 'text-lg md:text-xl font-semibold text-slate-900'
                    }`}>
                    {isDatePlan ? renderFormattedText(s.reply) : `"${s.reply}"`}
                  </div>

                  <p className={`text-xs mt-3 font-medium leading-snug border-t pt-3 ${theme === 'dark'
                      ? 'text-slate-500 border-slate-700/50'
                      : 'text-slate-600 border-gray-200'
                    }`}>
                    💡 {s.explanation}
                  </p>
                </div>

                <button
                  onClick={() => copyToClipboard(s.reply, idx)}
                  className={`p-3 rounded-full transition-all shrink-0 active:scale-95 hover:scale-110 ${theme === 'dark'
                      ? 'hover:bg-slate-700 bg-slate-900/60 text-slate-400 hover:text-white'
                      : 'hover:bg-gray-100 bg-white text-slate-600 hover:text-slate-900 shadow-sm'
                    }`}
                  title="Copy"
                >
                  {copiedIndex === idx ? <Check size={18} className="text-green-500" /> : <Copy size={18} />}
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* Actions */}
      <div className="flex gap-3 justify-center text-sm">
        <button
          onClick={copyAll}
          className={`transition-all flex items-center gap-2 px-4 py-2.5 rounded-xl font-semibold hover:scale-105 active:scale-95 ${theme === 'dark'
              ? 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
              : 'text-slate-600 hover:text-slate-900 hover:bg-gray-100'
            }`}
        >
          <Copy size={16} /> Copy All
        </button>
        <button
          onClick={shareResult}
          className={`transition-all flex items-center gap-2 px-4 py-2.5 rounded-xl font-semibold hover:scale-105 active:scale-95 ${theme === 'dark'
              ? 'text-slate-400 hover:text-pink-400 hover:bg-slate-800'
              : 'text-slate-600 hover:text-pink-600 hover:bg-pink-50'
            }`}
        >
          <Share2 size={16} /> Share
        </button>
      </div>

      {/* Grounding Links */}
      {result.groundingLinks && result.groundingLinks.length > 0 && (
        <div className={`rounded-xl p-4 border ${theme === 'dark'
            ? 'bg-slate-900/40 border-slate-800/50'
            : 'bg-gray-50/50 border-gray-200'
          }`}>
          <p className={`text-xs uppercase tracking-wider font-extrabold mb-3 ${theme === 'dark' ? 'text-slate-500' : 'text-slate-600'
            }`}>Sources & References</p>
          <div className="flex flex-col gap-2.5">
            {result.groundingLinks.map((link, i) => (
              <a
                key={i}
                href={link.url}
                target="_blank"
                rel="noopener noreferrer"
                className={`flex items-center gap-2 text-xs transition-all hover:scale-[1.02] hover:underline decoration-2 underline-offset-4 ${theme === 'dark'
                    ? 'text-blue-400 hover:text-blue-300 decoration-blue-500/30'
                    : 'text-blue-600 hover:text-blue-700 decoration-blue-500/30'
                  }`}
              >
                <ExternalLink size={14} className="shrink-0" />
                <span className="truncate font-medium">{link.title}</span>
              </a>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default ResultCard;