import React, { useState } from 'react';
import { AnalysisResult } from '../types';
import { Copy, Heart, Smile, Sparkles, Briefcase, ExternalLink, Skull, Zap, Share2, Check, Calendar } from 'lucide-react';

interface ResultCardProps {
  result: AnalysisResult;
}

const ToneIcon = ({ tone }: { tone: string }) => {
  const t = tone.toLowerCase();
  if (t.includes('flirt')) return <Heart className="w-4 h-4 text-pink-500" />;
  if (t.includes('fun') || t.includes('wit')) return <Smile className="w-4 h-4 text-yellow-500" />;
  if (t.includes('pro')) return <Briefcase className="w-4 h-4 text-blue-500" />;
  if (t.includes('unhinged')) return <Skull className="w-4 h-4 text-red-500" />;
  if (t.includes('casual')) return <Zap className="w-4 h-4 text-green-400" />;
  if (t.includes('date') || t.includes('plan')) return <Calendar className="w-4 h-4 text-emerald-400" />;
  return <Sparkles className="w-4 h-4 text-purple-500" />;
};

const ResultCard: React.FC<ResultCardProps> = ({ result }) => {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const copyToClipboard = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const copyAll = () => {
    const allText = result.suggestions.map(s => `${s.tone}: ${s.reply}`).join('\n\n');
    navigator.clipboard.writeText(allText);
    alert("All suggestions copied!");
  };

  const shareResult = async () => {
    const text = `Check out these rizz lines generated by RizzMaster AI:\n\n` + 
                 result.suggestions.map(s => `"${s.reply}"`).join('\n') + 
                 `\n\nGenerated by Vishesh's RizzMaster AI`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'RizzMaster AI Results',
          text: text,
          url: window.location.href
        });
      } catch (err) {
        console.log('Error sharing:', err);
      }
    } else {
      copyAll();
    }
  };

  // Helper to render text with simple formatting
  const renderFormattedText = (text: string) => {
      return text.split('\n').map((line, i) => (
          <span key={i} className="block min-h-[1.2em]">
            {line.split(/(\*\*.*?\*\*)/).map((part, j) => {
                if (part.startsWith('**') && part.endsWith('**')) {
                    return <strong key={j} className="text-white font-semibold">{part.slice(2, -2)}</strong>;
                }
                return part;
            })}
          </span>
      ));
  };

  return (
    <div className="flex flex-col gap-6 animate-fade-in-up w-full">
      {/* Summary Section */}
      {result.summary && (
        <div className="flex items-start gap-3 px-2 bg-slate-900/40 p-3 rounded-lg border border-slate-800/50">
            <div className="mt-1 shrink-0">
                <Sparkles className="w-4 h-4 text-purple-400" />
            </div>
            <p className="text-slate-300 text-sm italic leading-relaxed">{result.summary}</p>
        </div>
      )}

      {/* Suggestions Grid */}
      <div className="flex flex-col gap-3">
        {result.suggestions.map((s, idx) => {
          const isDatePlan = s.tone.toLowerCase().includes('date') || s.tone.toLowerCase().includes('plan');
          
          return (
            <div 
                key={idx} 
                className={`rounded-xl p-3 md:p-4 border transition-all group relative ${
                    isDatePlan 
                    ? 'bg-slate-900/90 border-emerald-500/30 hover:border-emerald-500/50 hover:shadow-[0_0_20px_rgba(16,185,129,0.1)]' 
                    : 'bg-slate-800/80 border-slate-700/60 hover:border-pink-500/30 hover:shadow-[0_0_15px_rgba(236,72,153,0.1)]'
                }`}
            >
                <div className="flex justify-between items-start gap-3 md:gap-4">
                    <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-2">
                            <ToneIcon tone={s.tone} />
                            <span className={`text-[10px] md:text-xs font-bold uppercase tracking-wider truncate ${
                                isDatePlan ? 'text-emerald-400' :
                                s.tone.toLowerCase().includes('flirty') ? 'text-pink-400' : 
                                s.tone.toLowerCase().includes('unhinged') ? 'text-red-400' : 'text-slate-400'
                            }`}>
                                {s.tone}
                            </span>
                        </div>
                        
                        <div className={`font-sans leading-relaxed selection:bg-pink-500/30 break-words ${
                            isDatePlan ? 'text-sm md:text-base text-slate-200' : 'text-base md:text-lg font-medium text-white'
                        }`}>
                            {isDatePlan ? renderFormattedText(s.reply) : `"${s.reply}"`}
                        </div>

                        <p className="text-[10px] md:text-xs text-slate-500 mt-2 font-medium leading-normal border-t border-slate-700/50 pt-2">
                            💡 {s.explanation}
                        </p>
                    </div>
                    
                    <button 
                    onClick={() => copyToClipboard(s.reply, idx)}
                    className="p-2.5 rounded-full hover:bg-slate-700 bg-slate-900/50 text-slate-400 hover:text-white transition-all shrink-0 active:scale-95"
                    title="Copy"
                    >
                    {copiedIndex === idx ? <Check size={18} className="text-green-400" /> : <Copy size={18} />}
                    </button>
                </div>
            </div>
          );
        })}
      </div>

      {/* Actions */}
      <div className="flex gap-3 justify-center text-sm">
        <button onClick={copyAll} className="text-slate-500 hover:text-slate-300 transition-colors flex items-center gap-1.5 px-3 py-1.5 rounded-lg hover:bg-slate-800">
            <Copy size={14} /> Copy All
        </button>
        <button onClick={shareResult} className="text-slate-500 hover:text-pink-400 transition-colors flex items-center gap-1.5 px-3 py-1.5 rounded-lg hover:bg-slate-800">
            <Share2 size={14} /> Share
        </button>
      </div>

      {/* Grounding Links - Enhanced Design */}
      {result.groundingLinks && result.groundingLinks.length > 0 && (
        <div className="mt-2 bg-slate-900/30 rounded-lg p-3 border border-slate-800/50">
           <p className="text-[10px] uppercase tracking-wider text-slate-500 font-bold mb-2">Sources & References</p>
           <div className="flex flex-col gap-2">
             {result.groundingLinks.map((link, i) => (
               <a 
                 key={i} 
                 href={link.url} 
                 target="_blank" 
                 rel="noopener noreferrer"
                 className="flex items-center gap-2 text-xs text-blue-400 hover:text-blue-300 transition-colors hover:underline decoration-blue-500/30 underline-offset-4"
               >
                 <ExternalLink size={12} className="shrink-0" /> 
                 <span className="truncate">{link.title}</span>
               </a>
             ))}
           </div>
        </div>
      )}
    </div>
  );
};

export default ResultCard;